services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: hackathon
    environment:
      POSTGRES_DB: shadow_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Familyyg1@
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "5433:5432"
